version: "3"

services:
  db:
    image: mongo
    restart: unless-stopped
    hostname: db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
      - MONGO_INITDB_DATABASE=${DB_NAME}
    expose:
      - 27017
    volumes:
      - db_volume:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    command: mongod --quiet --logpath /dev/null

  server:
    build:
      context: ./server
      target: production
    hostname: express
    expose:
      - ${PORT}
    depends_on:
      - db
    env_file:
      - ./server/.env
    links:
      - db

  client:
    build:
      context: ./client
      target: production
    ports:
      - "3000:3000"
    env_file:
      - ./client/.env

  nginx:
    image: nginx
    depends_on:
      - db
      - server
      - client
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./client/.next:/usr/share/nginx/html
      - ./server/dist:/usr/share/nginx/html/api

volumes:
  db_volume:
