version: "3"

services:
  db:
    image: mongo
    restart: unless-stopped
    hostname: db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
      - MONGO_INITDB_DATABASE=${DB_NAME}
    expose:
      - 27017
    volumes:
      - db_volume:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    command: mongod --quiet --logpath /dev/null

  client:
    restart: on-failure
    build:
      context: .
      target: client_build
    hostname: client
    expose:
      - 3000

  server:
    restart: on-failure
    build:
      context: .
      target: server_production
    hostname: server
    env_file:
      - .env
      - .env.production
    expose:
      - ${PORT}
    depends_on:
      - db
    links:
      - db

  nginx:
    image: nginx:1.25.4-alpine
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./nginx/:/etc/nginx/conf.d/:ro
      - ./certbot/www/:/var/www/certbot/:ro
      - ./certbot/letsencrypt/:/etc/letsencrypt/:rw

  certbot:
    image: certbot/certbot:v2.9.0
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/letsencrypt/:/etc/letsencrypt/:rw

volumes:
  db_volume:
