version: "3"

services:
  db:
    image: mongo
    restart: unless-stopped
    hostname: db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
      - MONGO_INITDB_DATABASE=${DB_NAME}
    ports:
      - ${DB_PORT}:27017
    volumes:
      - db_volume:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    command: mongod --quiet --logpath /dev/null

  server:
    env_file:
      - ./server/.env
    build:
      context: ./server
      target: development
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - db
    volumes:
      - ./server:/app
    links:
      - db

  client:
    env_file:
      - ./client/.env
    build:
      context: ./client
      target: development
    ports:
      - "3000:3000"
    depends_on:
      - db
      - server
    volumes:
      - ./client:/app

volumes:
  db_volume:
