version: "3"

services:
  db:
    image: mysql:8.0
    restart: unless-stopped
    hostname: db
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_TCP_PORT=${DB_PORT}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - db_volume:/var/lib/mysql
      - ./mysql-init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  server:
    env_file:
      - .env
      - .env.development
    build:
      context: .
      target: server_development
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - db
    volumes:
      - ./server:/app
      - /app/node_modules
    links:
      - db

  client:
    build:
      context: .
      target: client_development
    ports:
      - "3000:3000"
    depends_on:
      - db
      - server
    volumes:
      - ./client:/app
      - /app/node_modules

volumes:
  db_volume:
