import Head from "next/head";
import { Sidebar } from "../Sidebar";
import { Navigation } from "./Navigation";
import { PropsWithChildren, ReactNode } from "react";
import { cn } from "@/utils";

type AccountLayoutProps = {
  className?: string;
  children?: ReactNode;
};

export const AccountLayout = ({ children, className }: AccountLayoutProps) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={cn(["with-sidebar", "account", className])}>
        <Sidebar>
          <Navigation />
        </Sidebar>

        <div className="with-sidebar__content">
          <section className="container">{children}</section>
        </div>
      </div>
    </>
  );
};
