import { IconButton } from "@/components/Button";
import { CardsContainer } from "@/components/Cards";
import { ShowMore } from "@/components/Cards/ShowMore";
import { Picker } from "@/components/Picker";
import { PickerSection } from "@/components/Picker/PickerSection";
import { usePickerSectionData } from "@/components/Picker/hooks/usePickerSectionData";
import { SelectOption } from "@/components/Select/types";
import { SidebarFilters } from "@/components/Sidebar";
import { SwapIcon } from "@/components/svg/icons";
import { recommendationCars, sidebarInputs } from "@/constants/mockupData";
import Head from "next/head";
import React, { useCallback, useMemo, useState } from "react";

export default function SpecificCategory() {
  const [filters, setFilters] = useState(sidebarInputs);

  const onChangeFilters = useCallback(
    (inputGroupName: string, inputName: string, newValue: boolean | number) => {
      setFilters((prevFilters) => {
        const groupInputs = prevFilters[inputGroupName];
        const input = groupInputs.find(({ name }) => name === inputName);

        if (!input) return prevFilters;

        input.value = newValue;

        return {
          ...prevFilters,
          [inputGroupName]: [...groupInputs],
        };
      });
    },
    [],
  );

  const [recommendationCarsDisplayLimit, setRecommendationCarsDisplayLimit] =
    useState(8);

  const recommendationCarsToDisplay = useMemo(() => {
    return recommendationCars.slice(0, recommendationCarsDisplayLimit);
  }, [recommendationCarsDisplayLimit]);

  const {
    pickUpData,
    setPickUpData,
    dropOffData,
    setDropOffData,
    onSwapButtonClick,
  } = usePickerSectionData();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="with-sidebar">
        <SidebarFilters
          inputs={filters}
          onChangeFilters={onChangeFilters}
          hidden={false}
        />

        <div className="with-sidebar__content">
          <PickerSection
            className="container"
            pickUpData={pickUpData}
            setPickUpData={setPickUpData}
            dropOffData={dropOffData}
            setDropOffData={setDropOffData}
            onSwapButtonClick={onSwapButtonClick}
          />

          <section className="container cards__section cards__section--recommended">
            <CardsContainer
              cards={recommendationCarsToDisplay}
              title="Recomendation cars"
            />
            <ShowMore
              step={8}
              totalItemsCount={recommendationCars.length}
              itemsToShowLimit={recommendationCarsDisplayLimit}
              setItemsToShowLimit={setRecommendationCarsDisplayLimit}
              itemNamePlural="cars"
              itemNameSingular="car"
            />
          </section>
        </div>
      </div>
    </>
  );
}
