import Head from "next/head";
import { IconButton } from "@/components/Button";
import { SwapIcon } from "@/components/svg/icons";
import { Banner } from "@/components/Banner";
import bannerCar1 from "@/assets/img/banner_car_1.png";
import bannerCar2 from "@/assets/img/banner_car_2.png";
import { Picker } from "@/components/Picker";
import { useMemo, useState } from "react";
import { SelectOption } from "@/components/Select/types";
import { CardsContainer } from "@/components/Cards";
import { ShowMore } from "@/components/Cards/ShowMore";
import { popularCarsMockup, recommendationCars } from "@/constants/mockupData";

export default function Home() {
  const [recommendationCarsDisplayLimit, setRecommendationCarsDisplayLimit] =
    useState(8);

  const recommendationCarsToDisplay = useMemo(() => {
    return recommendationCars.slice(0, recommendationCarsDisplayLimit);
  }, [recommendationCarsDisplayLimit]);

  const [pickUpLocation, setPickUpLocation] = useState<SelectOption>();
  const [pickUpDate, setPickUpDate] = useState<Date>();
  const [pickUpTime, setPickUpTime] = useState<SelectOption>();

  const [dropOffLocation, setDropOffLocation] = useState<SelectOption>();
  const [dropOffDate, setDropOffDate] = useState<Date>();
  const [dropOffTime, setDropOffTime] = useState<SelectOption>();

  const onSwapButtonClick = () => {
    setPickUpLocation(dropOffLocation);
    setPickUpDate(dropOffDate);
    setPickUpTime(dropOffTime);
    setDropOffLocation(pickUpLocation);
    setDropOffDate(pickUpDate);
    setDropOffTime(pickUpTime);
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className="container banner__section">
        <Banner
          variant="light"
          title="The Best Platform for Car Rental"
          description="Ease of doing a car rental safely and reliably. Of course at a low price."
          buttonText="Rental car"
          href="/rental"
          carPicture={bannerCar1}
        />
        <Banner
          variant="dark"
          title="Easy way to rent a car at a low price"
          description="Providing cheap car rental services and safe and comfortable facilities."
          buttonText="Rental car"
          href="/rental"
          carPicture={bannerCar2}
        />
      </section>
      <section className="container pickers__section">
        <Picker
          date={pickUpDate}
          setDate={setPickUpDate}
          location={pickUpLocation}
          setLocation={setPickUpLocation}
          time={pickUpTime}
          setTime={setPickUpTime}
          headerTitle="Pick - up"
          pointMarkVariant="dark"
        />
        <div className="pickers__placeholder"></div>
        <IconButton
          size="lg"
          className="picker__swap-button"
          onClick={onSwapButtonClick}
        >
          <SwapIcon />
        </IconButton>
        <Picker
          date={dropOffDate}
          setDate={setDropOffDate}
          location={dropOffLocation}
          setLocation={setDropOffLocation}
          time={dropOffTime}
          setTime={setDropOffTime}
          headerTitle="drop - off"
          className="picker--drop-off"
          pointMarkVariant="light"
        />
      </section>
      <section className="container cards__section">
        <CardsContainer
          cards={popularCarsMockup}
          title="Popular cars"
          rightLink={{ href: "/popular", content: "view all" }}
          horizontalScrolling
        />
      </section>
      <section className="container cards__section cards__section--recommended">
        <CardsContainer
          cards={recommendationCarsToDisplay}
          title="Recomendation cars"
          horizontalScrolling
        />
        <ShowMore
          step={8}
          totalItemsCount={recommendationCars.length}
          itemsToShowLimit={recommendationCarsDisplayLimit}
          setItemsToShowLimit={setRecommendationCarsDisplayLimit}
          itemNamePlural="cars"
          itemNameSingular="car"
        />
      </section>
    </>
  );
}
