import Head from "next/head";
import Image from "next/image";
import { Button, ButtonWIcon, IconButton } from "@/components/Button";
import { SwapIcon, TurnOnWifiIcon } from "@/components/svg/icons";
import { Banner } from "@/components/Banner";
import bannerCar1 from "@/assets/img/banner_car_1.png";
import bannerCar2 from "@/assets/img/banner_car_2.png";
import { Picker } from "@/components/Picker";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className="container banner__section">
        <Banner
          variant="light"
          title="The Best Platform for Car Rental"
          description="Ease of doing a car rental safely and reliably. Of course at a low price."
          buttonText="Rental car"
          href="/rental"
          carPicture={bannerCar1}
        />
        <Banner
          variant="dark"
          title="Easy way to rent a car at a low price"
          description="Providing cheap car rental services and safe and comfortable facilities."
          buttonText="Rental car"
          href="/rental"
          carPicture={bannerCar2}
        />
      </section>
      <section className="container pickers__section">
        <Picker />
        <IconButton size="lg" className="picker__swap-button">
          <SwapIcon />
        </IconButton>
        <Picker />
      </section>
    </>
  );
}
