export const countries = {
    AFG: ['Afganistan'],
    ALB: ['Albania'],
    ALG: ['Algeria'],
    SAA: [
        'American Samoa',
        'Samoa (American)',
        'USA &gt;&gt; American Samoa'
    ],
    AND: ['Andorra'],
    AGL: ['Angola'],
    AGI: ['Anguilla'],
    ATG: ['Antigua &amp; Barbuda'],
    UAE: ['Arab Emirates (United)', 'United Arab Emirates'],
    ARG: ['Argentina'],
    ARM: ['Armenia'],
    ARU: ['Aruba'],
    AUS: ['Australia'],
    CHR: ['Australia &gt;&gt; Christmas Island', 'Christmas Island'],
    NFK: ['Australia &gt;&gt; Norfolk', 'Norfolk'],
    AUT: ['Austria'],
    AZE: ['Azerbaijan'],
    AZR: ['Azores', 'Portugal &gt;&gt; Azores'],
    BAH: ['Bahamas'],
    BHR: ['Bahrain'],
    BNG: ['Bangladesh'],
    BRB: ['Barbados'],
    BLR: ['Belarus'],
    BEL: ['Belgium'],
    BLZ: ['Belize'],
    BEN: ['Benin'],
    BER: ['Bermuda'],
    BHU: ['Bhutan'],
    BOL: ['Bolivia'],
    BOS: ['Bosnia &amp; Herzegovina'],
    BOT: ['Botswana'],
    BRA: ['Brazil'],
    BRU: ['Brunei Darussalam'],
    BUL: ['Bulgaria'],
    BFS: ['Burkina Faso'],
    MMR: ['Burma (Myanmar)', 'Myanmar'],
    BDI: ['Burundi'],
    CBG: ['Cambodia'],
    CAM: ['Cameroon'],
    CAN: ['Canada'],
    ICA: ['Canary Islands', 'Spain / Canary'],
    CAV: ['Cape Verde'],
    CYM: ['Cayman Islands'],
    CAF: ['Central African Rep.'],
    TCD: ['Chad'],
    JER: [
        'Channel Islands',
        'Great Brit.&gt;&gt; Jersey/Guernsey',
        'Jersey &amp; Guernsey'
    ],
    CHL: ['Chile'],
    CHN: ['China'],
    HKG: ['China &gt;&gt; Hong Kong', 'Hong Kong'],
    MAC: ['China &gt;&gt; Macau', 'Macau'],
    TAI: ['China &gt;&gt; Taiwan', 'Taiwan'],
    COL: ['Colombia'],
    COM: ['Comoros'],
    COG: ['Congo'],
    ZAI: ['Congo Dem. Rep.', 'Zaire (Congo Dem.Rep)'],
    COK: ['Cook Islands'],
    CRI: ['Costa Rica'],
    CRO: ['Croatia'],
    CUB: ['Cuba'],
    CYP: ['Cyprus'],
    TCH: ['Czech Rep.'],
    DNK: ['Denmark'],
    FRO: ['Denmark &gt;&gt; Faroe Islands', 'Faroe Islands'],
    DJI: ['Djibouti'],
    DMA: ['Dominica'],
    DOM: ['Dominican Rep.'],
    TIM: ['East Timor'],
    ECU: ['Ecuador'],
    EGY: ['Egypt'],
    GNE: ['Equatorial Guinea', 'Guinea (Equat.)'],
    ERI: ['Eritrea'],
    EST: ['Estonia'],
    ETH: ['Ethiopia'],
    FLK: ['Falkland Islands'],
    FIJ: ['Fiji'],
    FIN: ['Finland'],
    FRA: ['France'],
    GDL: ['France &gt;&gt; Guadeloupe', 'Guadeloupe'],
    GIA: ['France &gt;&gt; French Guiana', 'Guiana (French)'],
    MTN: ['France &gt;&gt; Martinique', 'Martinique'],
    MYT: ['France &gt;&gt; Mayotte', 'Mayotte'],
    NCL: ['France &gt;&gt; New Caledonia', 'New Caledonia'],
    PFR: ['France &gt;&gt; French Polynesia', 'Polynesia (French)'],
    REU: ['France &gt;&gt; Reunion', 'Reunion'],
    SPM: [
        'France &gt;&gt; St-Pierre/Miquelon',
        'Saint Pierre &amp; Miquelon'
    ],
    GAB: ['Gabon'],
    GAM: ['Gambia'],
    GEO: ['Georgia'],
    GER: ['Germany'],
    GHA: ['Ghana'],
    GIB: ['Gibraltar'],
    GBR: ['Great Britain', 'United Kingdom'],
    MAN: ['Great Brit.&gt;&gt; Isle of Man', 'Isle of Man', 'Man (Isle)'],
    GRE: ['Greece'],
    GRL: ['Greenland'],
    GRD: ['Grenada'],
    GUM: ['Guam', 'USA &gt;&gt; Guam'],
    GTM: ['Guatemala'],
    GUI: ['Guinea'],
    GNB: ['Guinea-Bissau'],
    GUY: ['Guyana'],
    HAI: ['Haiti'],
    HAW: ['Hawaii Islands', 'USA &gt;&gt; Hawaii'],
    HND: ['Honduras'],
    HUN: ['Hungary'],
    ISL: ['Iceland'],
    IND: ['India'],
    IDN: ['Indonesia'],
    IRQ: ['Iraq'],
    IRN: ['Iran'],
    IRL: ['Ireland'],
    ISR: ['Israel'],
    ITA: ['Italy'],
    CIV: ['Ivory Coast'],
    JAM: ['Jamaica'],
    JAP: ['Japan'],
    JOR: ['Jordan'],
    KAZ: ['Kazakhstan'],
    KEN: ['Kenya'],
    KIR: ['Kiribati'],
    KOR: ['Korea'],
    KUW: ['Kuwait'],
    KGZ: ['Kyrgyzstan'],
    LAO: ['Laos'],
    LAT: ['Latvia'],
    LIB: ['Lebanon'],
    LSO: ['Lesotho'],
    LBR: ['Liberia'],
    LBY: ['Libya'],
    LIE: ['Liechtenstein'],
    LIT: ['Lithuania'],
    LUX: ['Luxembourg'],
    MKD: ['Macedonia'],
    MAD: ['Madagascar'],
    MDR: ['Madeira', 'Portugal &gt;&gt; Madeira'],
    MWI: ['Malawi'],
    MLS: ['Malaysia'],
    MLD: ['Maldives'],
    MLI: ['Mali'],
    MLT: ['Malta'],
    MRN: ['Mariana Islands', 'Northern Mariana Isl.'],
    MHL: ['Marshall Islands'],
    MRT: ['Mauritania'],
    MRI: ['Mauritius'],
    MEX: ['Mexico'],
    MIC: ['Micronesia'],
    MOL: ['Moldova'],
    MCO: ['Monaco'],
    MNG: ['Mongolia'],
    MSR: ['Montserrat'],
    MAR: ['Morocco'],
    MOZ: ['Mozambique'],
    NAM: ['Namibia'],
    NRU: ['Nauru'],
    NEP: ['Nepal'],
    NED: ['Netherlands'],
    ATN: ['Netherlands Antilles'],
    NZL: ['New Zealand'],
    NIC: ['Nicaragua'],
    NGR: ['Niger'],
    NIU: ['Niue'],
    NIG: ['Nigeria'],
    NOR: ['Norway'],
    OMA: ['Oman'],
    PAK: ['Pakistan'],
    PLW: ['Palau'],
    PAL: ['Palestine'],
    PAN: ['Panama'],
    PNG: ['Papua New Guinea'],
    PAR: ['Paraguay'],
    PER: ['Peru'],
    PHL: ['Philippines'],
    PIT: ['Pitcairn'],
    POL: ['Poland'],
    PRT: ['Portugal'],
    PRI: ['Puerto Rico'],
    QAT: ['Qatar'],
    ROM: ['Romania'],
    RUS: ['Russia'],
    RWA: ['Rwanda'],
    SHE: ['Saint Helena'],
    SKN: ['Saint Kitts &amp; Nevis'],
    SLU: ['Saint Lucia'],
    VCT: ['Saint Vincent &amp; Grenadines'],
    SLV: ['Salvador'],
    SAM: ['Samoa (Western)', 'Western Samoa'],
    SMR: ['San Marino'],
    STP: ['Sao Tome &amp; Principe'],
    SAU: ['Saudi Arabia'],
    SEN: ['Senegal'],
    SEY: ['Seychelles'],
    SLE: ['Sierra Leone'],
    SGP: ['Singapore'],
    SLO: ['Slovakia'],
    SVN: ['Slovenia'],
    SLM: ['Solomon'],
    SOM: ['Somalia'],
    SAF: ['South Africa'],
    ESP: ['Spain'],
    SRI: ['Sri Lanka'],
    SDN: ['Sudan'],
    SUR: ['Suriname'],
    SWA: ['Swaziland'],
    SWE: ['Sweden'],
    SUI: ['Switzerland'],
    SYR: ['Syria'],
    TJK: ['Tajikistan'],
    TZA: ['Tanzania'],
    THA: ['Thailand'],
    TOG: ['Togo'],
    TOK: ['Tokelau'],
    TON: ['Tonga'],
    TRI: ['Trinidad &amp; Tobago'],
    TUN: ['Tunisia'],
    TUR: ['Turkey'],
    TKM: ['Turkmenistan'],
    TCA: ['Turks &amp; Caicos Islands'],
    TUV: ['Tuvalu'],
    UGA: ['Uganda'],
    UKR: ['Ukraine'],
    URU: ['Uruguay'],
    USA: ['USA'],
    ALA: ['USA &gt;&gt; Alaska'],
    UZB: ['Uzbekistan'],
    VAN: ['Vanuatu'],
    VAT: ['Vatican'],
    VEN: ['Venezuela'],
    VTN: ['Viet Nam'],
    VRG: ['Virgin Island GB'],
    VIR: ['Virgin Island US'],
    WAL: ['Wallis &amp; Futuna'],
    SAH: ['Western Sahara'],
    YEM: ['Yemen'],
    YUG: ['Yugoslavia'],
    ZAM: ['Zambia'],
    ZIM: ['Zimbabwe']
} as const

export const languages = [
    "English",
    "French",
    "German",
    "Dutch",
    "Italian",
    "Spanish",
    "Arabic",
    "Chinese",
    "Japanese",
    "Korean",
    "Russian",
    "Portuguese",
] as const

export const hobbies = {
    "A-Photo": "Photo",
    "E-Trips": "Trips",
    "I-Computing": "Computing, Video games",
    "M-Clothes": "Clothes",
    "B-Cinema": "Cinema, Television",
    "F-Sports": "Sports",
    "J-Politics": "Politics",
    "N-Sciences": "Sciences",
    "C-Music": "Music",
    "G-Reading": "Reading",
    "K-Animals": "Animals, Nature",
    "O-Cooking": "Cooking",
    "D-Collections": "Collections",
    "H-Painting": "Painting, Drawing, Art",
    "L-Astrology": "Astrology, Paranormal",
    "P-History": "History",
} as const

export const sex = ['F', 'M'] as const


export type CountryKey = keyof typeof countries
export type Language = typeof languages[number]
export type Hobby = keyof typeof hobbies
export type Sex = typeof sex[number]
