import { IconButton } from "@/components/Button";
import { CarDetail } from "@/components/CarDetail";
import { CardsContainer } from "@/components/Cards";
import { ShowMore } from "@/components/Cards/ShowMore";
import { Picker } from "@/components/Picker";
import { SelectOption } from "@/components/Select/types";
import { Sidebar } from "@/components/Sidebar";
import { SwapIcon } from "@/components/svg/icons";
import {
  carMockup,
  recommendationCars,
  sidebarInputs,
} from "@/constants/mockupData";
import Head from "next/head";
import React, { useCallback, useMemo, useState } from "react";

export default function SpecificCategory() {
  const [filters, setFilters] = useState(sidebarInputs);

  const onChangeFilters = useCallback(
    (inputGroupName: string, inputName: string, newValue: boolean | number) => {
      setFilters((prevFilters) => {
        const groupInputs = prevFilters[inputGroupName];
        const input = groupInputs.find(({ name }) => name === inputName);

        if (!input) return prevFilters;

        input.value = newValue;

        return {
          ...prevFilters,
          [inputGroupName]: [...groupInputs],
        };
      });
    },
    []
  );

  const [recommendationCarsDisplayLimit, setRecommendationCarsDisplayLimit] =
    useState(8);

  const recommendationCarsToDisplay = useMemo(() => {
    return recommendationCars.slice(0, recommendationCarsDisplayLimit);
  }, [recommendationCarsDisplayLimit]);

  const [pickUpLocation, setPickUpLocation] = useState<SelectOption>();
  const [pickUpDate, setPickUpDate] = useState<Date>();
  const [pickUpTime, setPickUpTime] = useState<SelectOption>();

  const [dropOffLocation, setDropOffLocation] = useState<SelectOption>();
  const [dropOffDate, setDropOffDate] = useState<Date>();
  const [dropOffTime, setDropOffTime] = useState<SelectOption>();

  const onSwapButtonClick = () => {
    setPickUpLocation(dropOffLocation);
    setPickUpDate(dropOffDate);
    setPickUpTime(dropOffTime);
    setDropOffLocation(pickUpLocation);
    setDropOffDate(pickUpDate);
    setDropOffTime(pickUpTime);
  };
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="category">
        <Sidebar
          inputs={filters}
          onChangeFilters={onChangeFilters}
          className="category__sidebar"
          hidden
        />

        <div className="category__content">
          <section className="container car-detail">
            <CarDetail data={carMockup} />
          </section>
          <section className="container cards__section cards__section--recommended">
            <CardsContainer
              cards={recommendationCarsToDisplay}
              title="Recent cars"
              horizontalScrolling
            />
            <ShowMore
              step={8}
              totalItemsCount={recommendationCars.length}
              itemsToShowLimit={recommendationCarsDisplayLimit}
              setItemsToShowLimit={setRecommendationCarsDisplayLimit}
              itemNamePlural="cars"
              itemNameSingular="car"
            />
          </section>
        </div>
      </div>
    </>
  );
}
