import { useHideNavigation } from "@/components/Layout/Navigation/useHideNavigation";
import { Steps } from "@/components/Rent/Steps/Steps";
import { Summary } from "@/components/Rent/Summary";
import { carMockup } from "@/constants/mockupData";
import Head from "next/head";
import { useRouter } from "next/router";
import React, { useState } from "react";

export default function CarRentPage() {
  const summaryToTop = useHideNavigation();
  const [summarySubtotal, setSummarySubtotal] = useState(80);
  const [summaryTax, setSummaryTax] = useState(0);

  const router = useRouter();
  const { carId } = router.query;

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="rent container">
        <Steps />
        <Summary
          toTop={summaryToTop}
          car={carMockup(carId)}
          subtotal={summarySubtotal}
          tax={summaryTax}
          total={80}
        />
      </div>
    </>
  );
}
